version: "3.8"
services:

    marketplace:
        environment:
            RECOMMENDATIONS_HOST: recommendations
        # DOCKER_BUILDKIT=1 docker build . -f marketplace/Dockerfile \
        #                   -t marketplace --secret id=ca.key,src=ca.key
        image: marketplace
        networks:
            - microservices
        ports:
            - 5000:5000

    recommendations:
        # DOCKER_BUILDKIT=1 docker build . -f recommendations/Dockerfile \
        #                   -t recommendations --secret id=ca.key,src=ca.key
        image: recommendations
        networks:
            - microservices
        ports:
            - 55051:55051
        links:
            - mysqldb
        volumes:
            - ./:/app

    mysqldb:
        image: mysql
        networks:
            - microservices
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=p@ssw0rd1
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql
volumes:
    mysql:
    mysql_config:

networks:
    microservices:
