version: "3.3"
services:

    # triton_service:
    #     image: triton_service
    #     networks:
    #         - microservices
    #     ports:
    #         - 8000:8000

    botegram:
        # environment:
        #     API_SERVICE_HOST: triton_service
        image: botegram
        networks:
            - microservices
        ports:
            - 55051:55051
        volumes:
            - ./:/app

networks:
    microservices:
