version: "3.8"
services:

    user_service:
        environment:
            API_SERVICE_HOST: api_service
        image: user_service
        networks:
            - microservices
        ports:
            - 5000:5000

    api_service:
        image: api_service
        networks:
            - microservices
        ports:
            - 55051:55051
        links:
            - mysqldb
        volumes:
            - ./:/app

    mysqldb:
        image: mysql
        networks:
            - microservices
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=p@ssw0rd1
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql
volumes:
    mysql:
    mysql_config:

networks:
    microservices:
